# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lululala?serverTimezone=Asia/Seoul
    username: lululala
    password: 1234
    
# mybatis
mybatis:
  type-aliases-package: boot.data.dto,boot.data.mapper
  mapper-locations:
  - /mapper/**/*.xml